# kubernetes/patches/services-nodeport.yaml
# Патчи для сервисов чтобы они были доступны через NodePort

---
# Патч для Airflow webserver
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  type: ClusterIP  # Оставляем ClusterIP, так как используем Ingress
  ports:
  - name: airflow-ui
    port: 8080
    targetPort: 8080
    protocol: TCP
---
# Патч для Grafana
apiVersion: v1
kind: Service
metadata:
  name: prometheus-stack-grafana
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: service
    port: 80
    targetPort: 3000
    protocol: TCP
---
# Прямой NodePort доступ (альтернатива Ingress)
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver-nodeport
  namespace: airflow
spec:
  type: NodePort
  selector:
    component: webserver
    tier: airflow
  ports:
  - name: airflow-ui
    port: 8080
    targetPort: 8080
    nodePort: 30080  # Фиксированный NodePort
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
  - name: service
    port: 3000
    targetPort: 3000
    nodePort: 30300  # Фиксированный NodePort
    protocol: TCP