apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.47.2
    chart: loki
    helm:
      valuesObject:
        # Использовать простой режим без Grafana Agent
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false
          server:
            http_listen_port: 3100
            grpc_listen_port: 9095

          commonConfig:
            replication_factor: 1
            path_prefix: /var/loki

          storage:
            type: filesystem

          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h

          limits_config:
            retention_period: 168h  # 7 дней
            enforce_metric_name: false
            reject_old_samples: true
            reject_old_samples_max_age: 168h
            max_entries_limit_per_query: 5000

        # Простой single binary режим
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: local-path
            size: 20Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        # Отключить все остальные компоненты
        write:
          replicas: 0
        read:
          replicas: 0
        backend:
          replicas: 0
        gateway:
          enabled: false

        # Отключить мониторинг компоненты которые вызывают проблемы
        monitoring:
          dashboards:
            enabled: false
          rules:
            enabled: false
          serviceMonitor:
            enabled: false
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false

        # Отключить тесты
        test:
          enabled: false

        # Создать сервис для доступа
        service:
          type: ClusterIP
          port: 3100

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true