apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.15.5
    chart: promtail
    helm:
      valuesObject:
        # Конфигурация Promtail
        config:
          # Сервер Loki
          clients:
          - url: http://loki.monitoring:3100/loki/api/v1/push
            tenant_id: 1

          # Позиции (где Promtail сохраняет прогресс)
          positions:
            filename: /run/promtail/positions.yaml

          # Конфигурация scrape
          snippets:
            # Общие настройки
            scrapeConfigs: |
              # Логи контейнеров k3s
              - job_name: kubernetes-pods
                kubernetes_sd_configs:
                - role: pod
                pipeline_stages:
                - cri: {}
                relabel_configs:
                - source_labels: [__meta_kubernetes_pod_node_name]
                  target_label: node
                - source_labels: [__meta_kubernetes_namespace]
                  target_label: namespace
                - source_labels: [__meta_kubernetes_pod_name]
                  target_label: pod
                - source_labels: [__meta_kubernetes_container_name]
                  target_label: container
                - source_labels: [__meta_kubernetes_pod_label_app]
                  target_label: app
                - action: replace
                  replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                  - __meta_kubernetes_pod_uid
                  - __meta_kubernetes_pod_container_name
                  target_label: __path__

        # DaemonSet для запуска на всех нодах
        daemonset:
          enabled: true

        # Важно! Правильные пути для k3s
        volumeMounts:
        - name: run
          mountPath: /run/promtail
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
        - name: containers
          mountPath: /var/lib/rancher/k3s/agent/containerd/io.containerd.grpc.v1.cri/containers
          readOnly: true

        volumes:
        - name: run
          hostPath:
            path: /run/promtail
        - name: pods
          hostPath:
            path: /var/log/pods
        - name: containers
          hostPath:
            path: /var/lib/rancher/k3s/agent/containerd/io.containerd.grpc.v1.cri/containers

        # Толерации для запуска на всех нодах включая master
        tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

        # Ресурсы
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

        # ServiceMonitor для мониторинга самого Promtail
        serviceMonitor:
          enabled: true
          labels:
            prometheus: kube-prometheus

        # Безопасность
        podSecurityPolicy:
          create: false

        rbac:
          create: true
          pspEnabled: false

        # Security context для доступа к логам
        containerSecurityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false

        podSecurityContext:
          runAsUser: 0
          runAsGroup: 0

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true