apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.21.4
    chart: kube-prometheus-stack
    helm:
      valuesObject:
        # Отключить некоторые компоненты временно
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
        prometheusOperator:
          # Создать ServiceAccount
          serviceAccount:
            create: true
            name: prometheus-operator
        prometheus:
          serviceAccount:
            create: true
            name: prometheus
          prometheusSpec:
            serviceAccountName: prometheus
            # ... остальные настройки
        # Добавить эти настройки
        defaultRules:
          create: true
          rules:
            alertmanager: true
            etcd: false
            general: true
            k8s: true
            kubeApiserver: false
            kubeApiserverAvailability: false
            kubeApiserverError: false
            kubeApiserverSlos: false
            kubelet: true
            kubePrometheusGeneral: true
            kubePrometheusNodeAlerting: true
            kubePrometheusNodeRecording: true
            kubernetesAbsent: true
            kubernetesApps: true
            kubernetesResources: true
            kubernetesStorage: true
            kubernetesSystem: true
            network: true
            node: true
            prometheus: true
            prometheusOperator: true
            time: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true