apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Monitoring stack (Prometheus, Grafana, Loki)

  sourceRepos:
  - 'https://prometheus-community.github.io/helm-charts'
  - 'https://grafana.github.io/helm-charts'
  - 'https://github.com/JeroniMan/k8s-otus-airflow'

  destinations:
  # Разрешить monitoring namespace
  - namespace: monitoring
    server: https://kubernetes.default.svc
  # Разрешить kube-system для сервисов мониторинга
  - namespace: kube-system
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: monitoring.coreos.com
    kind: '*'
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

  roles:
  - name: admin
    policies:
    - p, proj:monitoring:admin, applications, *, monitoring/*, allow
    groups:
    - monitoring-admins