global:
  domain: argocd.example.com

configs:
  params:
    server.insecure: true
    server.disable.auth: false

  cm:
    admin.enabled: "true"
    url: "https://argocd.example.com"

    resource.compareoptions: |
      ignoreAggregatedRoles: true

    resource.customizations: |
      admissionregistration.k8s.io/MutatingWebhookConfiguration:
        ignoreDifferences: |
          jsonPointers:
          - /webhooks/0/clientConfig/caBundle
      admissionregistration.k8s.io/ValidatingWebhookConfiguration:
        ignoreDifferences: |
          jsonPointers:
          - /webhooks/0/clientConfig/caBundle

server:
  replicas: 1
  autoscaling:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  service:
    type: NodePort
    nodePortHttp: 32080
    nodePortHttps: 32443

controller:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

repoServer:
  replicas: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

redis:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: true
  replicas: 1