# scripts/infrastructure/terraform-apply.sh
#!/bin/bash

set -e
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/validation.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/yandex-cloud.sh"

log STEP "Применение изменений Terraform"

# Загрузка окружения и валидация
load_env || exit 1
validate_env_vars || exit 1
validate_terraform_state || exit 1

# Экспорт S3 credentials
export_s3_credentials || exit 1

cd "${TERRAFORM_DIR}"

# Применение
if [ -f "tfplan" ]; then
    log INFO "Применение сохраненного плана..."
    terraform apply tfplan
    rm -f tfplan
else
    log INFO "Применение изменений..."
    terraform apply -auto-approve
fi

# Сохранение outputs
log INFO "Сохранение outputs..."
terraform output -json > "${PROJECT_ROOT}/terraform-outputs.json"

# Экспорт важных переменных
MASTER_IP=$(terraform output -json master_ips | jq -r '.["master-0"].public_ip')
LB_IP=$(terraform output -raw load_balancer_ip)

# Обновление .env
if [ -n "${MASTER_IP}" ] && [ -n "${LB_IP}" ]; then
    echo "" >> "${PROJECT_ROOT}/.env"
    echo "# Generated by Terraform" >> "${PROJECT_ROOT}/.env"
    echo "export MASTER_IP=${MASTER_IP}" >> "${PROJECT_ROOT}/.env"
    echo "export LB_IP=${LB_IP}" >> "${PROJECT_ROOT}/.env"
fi

log SUCCESS "Инфраструктура создана"
log INFO "Master IP: ${MASTER_IP}"
log INFO "Load Balancer IP: ${LB_IP}"