# scripts/infrastructure/terraform-destroy.sh
#!/bin/bash

set -e
source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/validation.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/yandex-cloud.sh"

log STEP "Удаление инфраструктуры Terraform"

# Подтверждение
log WARN "Это удалит ВСЮ инфраструктуру!"
read -p "Вы уверены? Введите 'yes' для подтверждения: " confirm

if [ "$confirm" != "yes" ]; then
    log INFO "Отменено"
    exit 0
fi

# Загрузка окружения и валидация
load_env || exit 1
validate_env_vars || exit 1
validate_terraform_state || exit 1

# Экспорт S3 credentials
export_s3_credentials || exit 1

cd "${TERRAFORM_DIR}"

# Удаление
log INFO "Удаление инфраструктуры..."
terraform destroy -auto-approve

# Очистка outputs
rm -f "${PROJECT_ROOT}/terraform-outputs.json"

# Очистка из .env
sed -i '/# Generated by Terraform/,/export LB_IP=/d' "${PROJECT_ROOT}/.env" 2>/dev/null || true

log SUCCESS "Инфраструктура удалена"