apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://airflow.apache.org/
    targetRevision: 1.11.0
    chart: airflow
    helm:
      values: |
        # Основные настройки
        executor: LocalExecutor
        
        # Образы
        defaultAirflowRepository: apache/airflow
        defaultAirflowTag: 2.8.1
        
        # Переменные окружения
        env:
          - name: AIRFLOW__CORE__LOAD_EXAMPLES
            value: "True"
        
        # Webserver
        webserver:
          replicas: 1
          service:
            type: NodePort
            ports:
              - name: airflow-ui
                port: 8080
                targetPort: 8080
                nodePort: 32080
          
          defaultUser:
            enabled: true
            role: Admin
            username: admin
            email: admin@example.com
            firstName: Admin
            lastName: User
            password: admin
        
        # Scheduler
        scheduler:
          replicas: 1
        
        # Workers - для LocalExecutor просто устанавливаем replicas в 0
        workers:
          replicas: 0
        
        # Redis отключен
        redis:
          enabled: false
        
        # PostgreSQL включен
        postgresql:
          enabled: true
          auth:
            postgresPassword: postgres
            username: airflow
            password: airflow
            database: airflow
        
        # Flower отключен
        flower:
          enabled: false
        
        # Triggerer отключен
        triggerer:
          enabled: false
        
        # DAGs из Git
        dags:
          gitSync:
            enabled: true
            repo: https://github.com/JeroniMan/k8s-otus-airflow.git
            branch: main
            subPath: airflow/dags
            wait: 60
        
        # Ingress отключен
        ingress:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m