apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://airflow.apache.org/
    targetRevision: 1.11.0
    chart: airflow
    helm:
      values: |
        airflowVersion: 2.8.1
        defaultAirflowRepository: apache/airflow
        defaultAirflowTag: 2.8.1

        executor: LocalExecutor

        serviceAccount:
          create: true
          name: airflow

        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
          serviceAccount:
            create: true
            name: airflow-create-user-job

        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
          serviceAccount:
            create: true
            name: airflow-migrate-database-job

        webserverSecretKey: "af7CN44BBsdfZOE8"
        fernetKey: "Z2uDm0ZL60fXNkEXG8LW99Ki2-cUFw9rm_aqhPdiTKU="

        defaultAirflowUsername: admin
        defaultAirflowPassword: admin
        defaultAirflowFirstName: Admin
        defaultAirflowLastName: User
        defaultAirflowEmail: admin@example.com
        defaultAirflowRole: Admin

        webserver:
          replicas: 1
          serviceAccount:
            create: true
            name: airflow-webserver
          service:
            type: NodePort
            ports:
              - name: airflow-ui
                port: 8080
                targetPort: 8080
                nodePort: 30880

        scheduler:
          replicas: 1
          serviceAccount:
            create: true
            name: airflow-scheduler

        postgresql:
          enabled: true
          auth:
            postgresPassword: postgres
            username: postgres
            password: postgres
            database: airflow
          persistence:
            enabled: true
            size: 8Gi
            storageClass: local-path
          service:
            port: 5432

        data:
          metadataConnection:
            user: postgres
            pass: postgres
            protocol: postgresql
            host: ~
            port: 5432
            db: airflow
            sslmode: disable

        redis:
          enabled: false

        workers:
          replicas: 0
          serviceAccount:
            create: true
            name: airflow-worker

        flower:
          enabled: false

        statsd:
          enabled: true
          serviceAccount:
            create: true
            name: airflow-statsd

        dags:
          persistence:
            enabled: false
          gitSync:
            enabled: true
            repo: https://github.com/JeroniMan/k8s-otus-airflow.git
            branch: main
            rev: HEAD
            depth: 1
            maxFailures: 0
            subPath: "airflow/dags"
            wait: 60
            containerName: git-sync
            uid: 65533

        logs:
          persistence:
            enabled: true
            size: 100Gi
            storageClassName: local-path

        ingress:
          enabled: false

        rbac:
          create: true
          createSCCRoleBinding: false

        securityContext:
          runAsUser: 50000
          runAsGroup: 0
          fsGroup: 0

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m