apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: https://airflow.apache.org/
    targetRevision: 1.11.0
    chart: airflow
    helm:
      values: |
        executor: LocalExecutor
        
        env:
          - name: AIRFLOW__CORE__LOAD_EXAMPLES
            value: "False"
          - name: AIRFLOW__CORE__EXECUTOR
            value: "LocalExecutor"
          - name: AIRFLOW__LOGGING__LOGGING_LEVEL
            value: "INFO"
          # Важно! Указываем где хранить логи
          - name: AIRFLOW__LOGGING__BASE_LOG_FOLDER
            value: "/opt/airflow/logs"
          - name: AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY
            value: "/opt/airflow/logs/scheduler"
        
        # Добавляем volumes для логов
        extraVolumes:
          - name: logs
            emptyDir: {}
        
        extraVolumeMounts:
          - name: logs
            mountPath: /opt/airflow/logs
        
        webserver:
          extraVolumes:
            - name: logs
              emptyDir: {}
          extraVolumeMounts:
            - name: logs
              mountPath: /opt/airflow/logs
          service:
            type: NodePort
            ports:
              - name: airflow-ui
                port: 8080
                targetPort: 8080
                nodePort: 32080
          defaultUser:
            enabled: true
            role: Admin
            username: admin
            email: admin@example.com
            firstName: Admin
            lastName: User
            password: admin
        
        scheduler:
          extraVolumes:
            - name: logs
              emptyDir: {}
          extraVolumeMounts:
            - name: logs
              mountPath: /opt/airflow/logs
        
        workers:
          extraVolumes:
            - name: logs
              emptyDir: {}
          extraVolumeMounts:
            - name: logs
              mountPath: /opt/airflow/logs
        
        postgresql:
          enabled: true
          auth:
            postgresPassword: postgres
            username: airflow
            password: airflow
            database: airflow
        
        redis:
          enabled: false
        
        flower:
          enabled: false
        
        statsd:
          enabled: false
        
        logs:
          persistence:
            enabled: false
        
        dags:
          persistence:
            enabled: false
          gitSync:
            enabled: true
            repo: https://github.com/JeroniMan/k8s-otus-airflow.git
            branch: main
            subPath: "airflow/dags"
            wait: 60
        
        createUserJob:
          useHelmHooks: false
        
        migrateDatabaseJob:
          enabled: true
          useHelmHooks: false

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    syncOptions:
    - CreateNamespace=true