apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    repoURL: https://airflow.apache.org/  # Правильный URL репозитория
    targetRevision: 1.11.0
    chart: airflow
    helm:
      valuesObject:
        # Образы
        defaultAirflowRepository: apache/airflow
        defaultAirflowTag: 2.8.1-python3.11
        airflowVersion: 2.8.1

        # Executor
        executor: KubernetesExecutor

        images:
          airflow:
            repository: apache/airflow
            tag: 2.8.1-python3.11
            pullPolicy: IfNotPresent

        # Переменные окружения
        env:
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "False"
        - name: AIRFLOW__KUBERNETES__NAMESPACE
          value: "airflow"
        - name: AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME
          value: "airflow-worker"
        - name: AIRFLOW__KUBERNETES__IN_CLUSTER
          value: "True"
        - name: AIRFLOW__METRICS__STATSD_ON
          value: "True"
        - name: AIRFLOW__METRICS__STATSD_HOST
          value: "airflow-statsd"
        - name: AIRFLOW__METRICS__STATSD_PORT
          value: "9125"
        - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
          value: "True"
        - name: AIRFLOW__CORE__PARALLELISM
          value: "32"
        - name: AIRFLOW__CORE__DAG_CONCURRENCY
          value: "16"
        - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS
          value: "True"
        - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS_ON_FAILURE
          value: "False"

        # Webserver
        webserver:
          replicas: 1
          resources:
            requests:
              memory: 1Gi
              cpu: 300m
            limits:
              memory: 2Gi
              cpu: 1

          # Service
          service:
            type: NodePort
            ports:
              - name: airflow-ui
                port: 8080
                nodePort: 32080

          # Default user
          defaultUser:
            enabled: true
            role: Admin
            username: admin
            email: admin@example.com
            firstName: Admin
            lastName: User
            password: admin

        # Scheduler
        scheduler:
          replicas: 1
          resources:
            requests:
              memory: 1Gi
              cpu: 300m
            limits:
              memory: 2Gi
              cpu: 1

        # Workers (для KubernetesExecutor)
        workers:
          resources:
            requests:
              memory: 1Gi
              cpu: 300m
            limits:
              memory: 2Gi
              cpu: 1

        # PostgreSQL
        postgresql:
          enabled: true
          auth:
            enablePostgresUser: true
            postgresPassword: postgres
            username: airflow
            password: airflow
            database: airflow

          primary:
            persistence:
              enabled: true
              size: 20Gi
              storageClass: local-path

            resources:
              requests:
                memory: 256Mi
                cpu: 250m
              limits:
                memory: 512Mi
                cpu: 500m

        # Redis не нужен для KubernetesExecutor
        redis:
          enabled: false

        # DAGs
        dags:
          persistence:
            enabled: false

          gitSync:
            enabled: true
            repo: https://github.com/JeroniMan/k8s-otus-airflow.git
            branch: main
            rev: HEAD
            depth: 1
            wait: 60
            subPath: "airflow/dags"

            resources:
              requests:
                memory: 64Mi
                cpu: 50m
              limits:
                memory: 128Mi
                cpu: 100m

        # Logs
        logs:
          persistence:
            enabled: true
            size: 50Gi
            storageClass: local-path

        # Ingress отключен, используем NodePort
        ingress:
          enabled: false

        # Создание пользователя без Helm hooks
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false

        # Secret key для webserver
        webserverSecretKey: "af7cn976UVRVf-dTI50-oao03p9r2fGEpU79XPuJOxc"

        # StatefulSet для StatsD
        statsd:
          enabled: true

        # Метрики
        metrics:
          enabled: true

        # Очистка старых задач
        cleanup:
          enabled: true
          schedule: "*/15 * * * *"

        # Не создавать ServiceAccount автоматически
        serviceAccount:
          create: false
          name: airflow

        # Security Context
        securityContext:
          runAsUser: 50000
          runAsGroup: 0
          fsGroup: 0

  destination:
    server: https://kubernetes.default.svc
    namespace: airflow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m