# kubernetes/namespaces/monitoring.yaml
# Namespace для системы мониторинга

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: monitoring-stack
    environment: production

---
# ResourceQuota для контроля ресурсов
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "20"
    limits.memory: "40Gi"
    persistentvolumeclaims: "20"
    services: "20"

---
# LimitRange для дефолтных лимитов подов
apiVersion: v1
kind: LimitRange
metadata:
  name: monitoring-limitrange
  namespace: monitoring
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "50m"
      memory: "64Mi"
    type: Container
  - max:
      storage: "50Gi"
    type: PersistentVolumeClaim

---
# NetworkPolicy - разрешаем доступ из всех namespaces для сбора метрик
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-network-policy
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}  # Разрешаем доступ из всех namespaces
  egress:
  - to:
    - namespaceSelector: {}  # Разрешаем доступ во все namespaces для сбора метрик
  - to:
    - podSelector: {}
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53