apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure

  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.51.6
    chart: argo-cd
    helm:
      releaseName: argocd
      values: |
        # ArgoCD configuration
        global:
          domain: argocd.example.com
          
        configs:
          params:
            server.insecure: true
            
          cm:
            # URL для UI
            url: "https://argocd.example.com"
            
            # Dex config for SSO (optional)
            dex.config: |
              connectors: []
              
            # Repository credentials
            repositories: |
              - url: https://github.com/YOUR_USERNAME/YOUR_REPO.git
                type: git
                
            # RBAC
            policy.default: role:readonly
            policy.csv: |
              p, role:admin, applications, *, */*, allow
              p, role:admin, clusters, *, *, allow
              p, role:admin, repositories, *, *, allow
              g, argocd-admins, role:admin
              
          rbac:
            policy.default: role:readonly
            
        # Server
        server:
          replicas: 2
          autoscaling:
            enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - argocd.example.com
            paths:
              - /
            tls:
              - secretName: argocd-tls
                hosts:
                  - argocd.example.com
                  
        # Repo server
        repoServer:
          replicas: 2
          autoscaling:
            enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
              
        # Controller
        controller:
          replicas: 1
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
              
        # Redis
        redis:
          enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
              
        # Dex (for SSO)
        dex:
          enabled: false
          
        # Notifications (optional)
        notifications:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false  # Namespace должен уже существовать
    - RespectIgnoreDifferences=true
    -