apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure

  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.15.5
    chart: promtail
    helm:
      values: |
        {{- .Files.Get "helm-values/promtail/values-base.yaml" | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false