apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.21.4
    chart: kube-prometheus-stack
    helm:
      values: |
        {{- .Files.Get "helm-values/prometheus/values-base.yaml" | nindent 8 }}

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - ServerSideApply=true
    - RespectIgnoreDifferences=true

  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: prometheus-kube-prometheus-admission
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: prometheus-kube-prometheus-admission
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle