# Дополнительные права для k3s нод для работы с PVC
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:k3s-node-pvc
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:k3s-node-pvc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:k3s-node-pvc
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes