apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/airflow.yaml
  - namespaces/monitoring.yaml
  - namespaces/argocd.yaml
  - rbac/airflow-sa.yaml
  - rbac/airflow-role.yaml
  - rbac/airflow-rolebinding.yaml
  - configmaps/airflow-dags.yaml