apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yc-network-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: disk-csi-driver.mks.yandexcloud.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: network-ssd
  csi.storage.k8s.io/fstype: ext4
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yc-network-hdd
provisioner: disk-csi-driver.mks.yandexcloud.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: network-hdd
  csi.storage.k8s.io/fstype: ext4