grafana:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 30d
    
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: yc-network-ssd
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
    
    externalLabels:
      cluster: yandex-managed-k8s
      region: ru-central1
    
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    
    additionalScrapeConfigs:
    - job_name: 'airflow-statsd'
      static_configs:
      - targets: ['airflow-statsd.airflow.svc.cluster.local:9102']

alertmanager:
  alertmanagerSpec:
    replicas: 1
    retention: 120h
    
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: yc-network-ssd
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['alertname', 'cluster', 'service']
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 12h
        receiver: 'default'
        routes:
        - match:
            severity: critical
          receiver: 'critical'
      receivers:
      - name: 'default'
      - name: 'critical'

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi