# kubernetes/helm-values/prometheus/values-base.yaml
# Убираем grafana отсюда, так как используем отдельный
prometheus:
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi

# ВАЖНО: Отключаем встроенную Grafana
grafana:
  enabled: false

alertmanager:
  alertmanagerSpec:
    replicas: 1
    retention: 120h
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

# Дополнительные scrape configs
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: 'airflow-statsd'
      static_configs:
      - targets: ['airflow-statsd.airflow.svc.cluster.local:9102']