# infrastructure/terraform/templates/inventory.tpl

# Глобальные переменные для всех хостов
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /Users/germankovalev/.ssh/k8s-airflow
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3

    # Kubernetes настройки
    k3s_version: "v1.28.5+k3s1"
    k3s_config_file: /etc/rancher/k3s/config.yaml

    # NFS настройки
    nfs_server_ip: 10.0.1.11
    nfs_path: /srv/nfs/k8s

    # Системные настройки
    system_timezone: "Europe/Moscow"

  children:
    # Группа master нод
    masters:
      hosts:
        k8s-airflow-prod-master-0:
          ansible_host: 46.21.245.246
          internal_ip: 10.0.1.11
          node_name: k8s-airflow-prod-master-0
      vars:
        node_type: master

    # Группа worker нод
    workers:
      hosts:
        k8s-airflow-prod-worker-0:
          ansible_host: 46.21.244.86
          internal_ip: 10.0.1.23
          node_name: k8s-airflow-prod-worker-0
        k8s-airflow-prod-worker-1:
          ansible_host: 84.201.130.251
          internal_ip: 10.0.1.15
          node_name: k8s-airflow-prod-worker-1
      vars:
        node_type: worker

    # Группа для k3s сервера (master)
    k3s_server:
      hosts:
        k8s-airflow-prod-master-0:

    # Группа для k3s агентов (workers)
    k3s_agent:
      hosts:
        k8s-airflow-prod-worker-0:
        k8s-airflow-prod-worker-1:
