# Grafana standalone configuration
replicas: 1

# Admin credentials
adminUser: admin
adminPassword: changeme123

# Persistence
persistence:
  enabled: true
  storageClassName: local-path
  size: 10Gi

# Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Ingress
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-cookie-name: "grafana-server"
    nginx.ingress.kubernetes.io/affinity-cookie-max-age: "86400"
  hosts:
    - ""
  path: /grafana
  pathType: Prefix

# Configure grafana.ini
grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
    serve_from_sub_path: true
  auth:
    disable_login_form: false
  auth.anonymous:
    enabled: true
    org_role: Viewer
  security:
    admin_user: admin
    admin_password: changeme123

# Datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus-uid
      url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 30s
    - name: Loki
      type: loki
      uid: loki-uid
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      jsonData:
        maxLines: 1000

# Dashboard providers
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards/default
    - name: 'airflow'
      orgId: 1
      folder: 'Airflow'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      options:
        path: /var/lib/grafana/dashboards/airflow

# Sidecar for loading dashboards from ConfigMaps
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards
    searchNamespace: ALL
    provider:
      allowUiUpdates: true
      foldersFromFilesStructure: true
  datasources:
    enabled: false  # We define datasources above

# Enable plugins
plugins:
  - grafana-clock-panel
  - grafana-simple-json-datasource
  - grafana-piechart-panel

# RBAC
rbac:
  create: true
  pspEnabled: false

serviceAccount:
  create: true
  name: grafana