# kubernetes/manifests/storage/storage-class.yaml
# Storage Class для динамического провижининга через NFS

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs-subdir-external-provisioner # Должен совпадать с именем в NFS provisioner
parameters:
  archiveOnDelete: "true"  # Архивировать PV при удалении PVC
  pathPattern: "${.PVC.namespace}/${.PVC.name}"  # Паттерн пути на NFS сервере
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate

---
# Storage Class для локального хранилища (для тестов)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
# Storage Class для критичных данных (Retain)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-retain
provisioner: nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"
  pathPattern: "${.PVC.namespace}/${.PVC.name}"
reclaimPolicy: Retain  # НЕ удалять данные при удалении PVC
allowVolumeExpansion: true
volumeBindingMode: Immediate