# kubernetes/helm-values/ingress-nginx/values-base.yaml
controller:
  # Service configuration
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
    externalTrafficPolicy: Local

  # Resources
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Replicas
  replicaCount: 2

  # Anti-affinity
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/component: controller
          topologyKey: kubernetes.io/hostname

  # Metrics
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        prometheus: kube-prometheus

  # Config
  config:
    proxy-body-size: "50m"
    proxy-read-timeout: "600"
    proxy-send-timeout: "600"
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"

  # HPA
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

  # PodDisruptionBudget
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

# Default backend
defaultBackend:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 50m
      memory: 50Mi

# RBAC
rbac:
  create: true

# ServiceAccount
serviceAccount:
  create: true