loki:
  auth_enabled: false
  
  storage:
    type: s3
    s3:
      endpoint: https://storage.yandexcloud.net
      region: ru-central1
      bucketNames:
        chunks: ${LOKI_S3_BUCKET}
        ruler: ${LOKI_S3_BUCKET}
        admin: ${LOKI_S3_BUCKET}
      accessKeyId: ${S3_ACCESS_KEY}
      secretAccessKey: ${S3_SECRET_KEY}
      s3ForcePathStyle: true
      insecure: false
  
  structuredConfig:
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    
    common:
      path_prefix: /loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
    
    schema_config:
      configs:
      - from: 2024-01-01
        store: tsdb
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h
    
    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/tsdb-index
        cache_location: /loki/tsdb-cache
        cache_ttl: 24h
      filesystem:
        directory: /loki/chunks
    
    limits_config:
      retention_period: 168h
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_entries_limit_per_query: 5000
      split_queries_by_interval: 15m
      max_chunks_per_query: 2000000
      max_query_parallelism: 32
    
    query_scheduler:
      max_outstanding_requests_per_tenant: 2048
    
    compactor:
      working_directory: /loki/retention
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      compaction_interval: 10m

singleBinary:
  replicas: 1
  
  persistence:
    enabled: true
    size: 20Gi
    storageClass: yc-network-ssd
  
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

read:
  replicas: 0

write:
  replicas: 0

backend:
  replicas: 0

gateway:
  enabled: false

monitoring:
  dashboards:
    enabled: true
    namespace: monitoring
    labels:
      grafana_dashboard: "1"
  
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      prometheus: kube-prometheus

test:
  enabled: false