# kubernetes/helm-values/loki/values-base.yaml
loki:
  auth_enabled: false

  # Исправляем структуру конфигурации
  structuredConfig:
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem  # Изменяем на filesystem для простоты
          schema: v12
          index:
            prefix: index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/tsdb-index
        cache_location: /loki/tsdb-cache
        cache_ttl: 24h

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_entries_limit_per_query: 5000

    compactor:
      working_directory: /loki/retention
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h

# Single Binary deployment
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi
    storageClass: local-path
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Отключаем компоненты для single binary
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

gateway:
  enabled: false

monitoring:
  dashboards:
    enabled: true
    namespace: monitoring
  serviceMonitor:
    enabled: true
    namespace: monitoring