apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-airflow-rules
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
    role: alert-rules
data:
  airflow.rules.yaml: |
    groups:
    - name: airflow
      interval: 30s
      rules:
      - alert: AirflowSchedulerDown
        expr: up{job="airflow-scheduler"} == 0
        for: 5m
        labels:
          severity: critical
          component: airflow
        annotations:
          summary: "Airflow Scheduler is down"
          description: "Airflow Scheduler has been down for more than 5 minutes"
          
      - alert: AirflowHighTaskFailureRate  
        expr: |
          (
            sum(rate(airflow_task_failed[5m])) by (dag_id)
            /
            sum(rate(airflow_task_success[5m]) + rate(airflow_task_failed[5m])) by (dag_id)
          ) > 0.1
        for: 10m
        labels:
          severity: warning
          component: airflow
        annotations:
          summary: "High task failure rate for DAG {{ $labels.dag_id }}"
          description: "More than 10% of tasks are failing for DAG {{ $labels.dag_id }}"