# Promtail configuration
config:
  clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
      tenant_id: 1

  snippets:
    pipelineStages:
      - cri: {}
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            msg: msg
            level: level
            ts: time
          source: output
      - regex:
          expression: '(?P<pod_uid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})'
          source: filename
      - labels:
          stream:
          level:
          pod_uid:
      - timestamp:
          format: RFC3339
          source: ts
      - output:
          source: msg

# Resources
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# DaemonSet configuration
daemonset:
  enabled: true

# RBAC
rbac:
  create: true
  pspEnabled: false

# Service account
serviceAccount:
  create: true
  name: promtail

# Tolerations for running on all nodes
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

# Volume mounts
defaultVolumes:
  - name: run
    hostPath:
      path: /run/promtail
  - name: pods
    hostPath:
      path: /var/log/pods
  - name: containers
    hostPath:
      path: /var/lib/docker/containers

defaultVolumeMounts:
  - name: run
    mountPath: /run/promtail
  - name: pods
    mountPath: /var/log/pods
    readOnly: true
  - name: containers
    mountPath: /var/lib/docker/containers
    readOnly: true

# Extra volume mounts for systemd journal
extraVolumes:
  - name: journal
    hostPath:
      path: /var/log/journal

extraVolumeMounts:
  - name: journal
    mountPath: /var/log/journal
    readOnly: true

# Service monitor for Prometheus
serviceMonitor:
  enabled: true
  labels:
    prometheus: kube-prometheus